version: "3.7"
services:
  node:
    build: .
    ports:
      - 3000:3000
      # - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: db1
    image: mongo
    ports:
      - "27018:27017"
